version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: transfer_system_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: transfer_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    networks:
      - transfer_system_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d transfer_system_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    stop_grace_period: 10s
    stop_signal: SIGINT

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfer_system_app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    networks:
      - transfer_system_network
    stop_grace_period: 60s
    stop_signal: SIGINT

networks:
  transfer_system_network:
    driver: bridge

volumes:
  postgres_data: